# Generated by Django 4.1.4 on 2024-06-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("factwiseapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factwiseapp.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="factwiseapp.user_base",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_teams",
                to="factwiseapp.user_base",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="factwiseapp.TeamMembership",
                to="factwiseapp.user_base",
            ),
        ),
    ]
